[package]
name = "minivault"
version = "0.0.0"

[addresses]
std = "0x1"
minivault = "_"

[dev-addresses]
minivault = "0x2"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "8399cd1c7b9662d3a6a09c28363c5f66f0839c41"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "8399cd1c7b9662d3a6a09c28363c5f66f0839c41"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "8399cd1c7b9662d3a6a09c28363c5f66f0839c41"